import React from 'react';
import { StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import AdminShell from '../../components/AdminShell';
import { CardSkeleton } from '../../components/AdminSkeleton';
import { StatusBadge } from '../../components/DashboardUi';
import LocationMap from '../../components/LocationMap';
import { BLUETAP_LAYOUT } from '../../constants/bluetapTheme';
import { useAdminTheme } from '../../components/AdminTheme';
import { createBranch, getBranches, updateBranch } from '../../services/branchManagement';
import { ADMIN_CACHE_KEYS, useAdminData } from '../../services/adminDataCache';

const empty = { name:'',code:'',barangay:'',city:'',address:'',latitude:'',longitude:'',serviceRadiusKm:'' };

export default function AdminBranchesPage() {
  const { colors } = useAdminTheme(); const styles = createStyles(colors);
  const { data,loading,refreshing,error,refresh } = useAdminData(ADMIN_CACHE_KEYS.branches,getBranches);
  const branches = data || []; const [form,setForm] = React.useState(empty); const [editingId,setEditingId] = React.useState(''); const [saving,setSaving] = React.useState(false); const [message,setMessage] = React.useState('');
  const edit = (branch) => { setEditingId(branch.id); setForm({name:branch.name,code:branch.code,barangay:branch.barangay,city:branch.city,address:branch.address,latitude:String(branch.latitude ?? ''),longitude:String(branch.longitude ?? ''),serviceRadiusKm:String(branch.serviceRadiusKm ?? '')}); setMessage(''); };
  const cancel = () => { setEditingId(''); setForm(empty); setMessage(''); };
  const setLocation = (location) => setForm((current)=>({...current,latitude:location.latitude.toFixed(6),longitude:location.longitude.toFixed(6)}));
  const save = async () => { setSaving(true); setMessage(''); try { const payload={name:form.name,barangay:form.barangay,city:form.city,address:form.address,latitude:Number(form.latitude),longitude:Number(form.longitude),serviceRadiusKm:form.serviceRadiusKm}; if(editingId) await updateBranch(editingId,payload); else await createBranch({...payload,code:form.code}); const wasEditing=Boolean(editingId); cancel(); await refresh({force:true}); setMessage(wasEditing?'Branch updated.':'Branch created.'); } catch(saveError){setMessage(saveError.message);} finally{setSaving(false);} };
  const toggle = async (branch) => { setSaving(true); setMessage(''); try { await updateBranch(branch.id,{status:branch.status==='active'?'inactive':'active'}); await refresh({force:true}); } catch(toggleError){setMessage(toggleError.message);} finally{setSaving(false);} };
  const previewLocation = Number.isFinite(Number(form.latitude)) && Number.isFinite(Number(form.longitude)) && form.latitude !== '' && form.longitude !== '' ? {latitude:Number(form.latitude),longitude:Number(form.longitude)} : null;
  return <AdminShell title="Branches" subtitle="Create provider locations and control where BlueTap orders can be fulfilled.">
    <View style={styles.formCard}><Text style={styles.eyebrow}>BRANCH DIRECTORY</Text><Text style={styles.cardTitle}>{editingId?'Edit branch':'Create branch'}</Text><Text style={styles.help}>Coordinates are required before a branch can appear as a Requester provider.</Text>
      <View style={styles.fields}>{[['name','Branch name'],['code','Code'],['barangay','Barangay'],['city','City'],['address','Address'],['latitude','Latitude'],['longitude','Longitude'],['serviceRadiusKm','Service radius (km, optional)']].map(([key,label])=><View key={key} style={styles.field}><Text style={styles.label}>{label}</Text><TextInput editable={key!=='code'||!editingId} value={form[key]} keyboardType={['latitude','longitude','serviceRadiusKm'].includes(key)?'decimal-pad':'default'} onChangeText={(value)=>setForm((current)=>({...current,[key]:value}))} style={[styles.input,key==='code'&&editingId&&styles.disabled]}/></View>)}</View>
      <Text style={styles.mapLabel}>Branch location</Text><LocationMap location={previewLocation} branches={[]} onLocationChange={setLocation}/>
      <View style={styles.actions}>{editingId&&<TouchableOpacity style={styles.secondary} onPress={cancel}><Text style={styles.secondaryText}>Cancel</Text></TouchableOpacity>}<TouchableOpacity disabled={saving} style={styles.primary} onPress={save}><Text style={styles.primaryText}>{saving?'Saving…':editingId?'Save changes':'Create branch'}</Text></TouchableOpacity></View>
    </View>
    {!!message&&<View accessibilityRole="alert" style={styles.notice}><Text style={styles.noticeText}>{message}</Text></View>}
    <View style={styles.listHeader}><View><Text style={styles.listTitle}>Existing branches</Text><Text style={styles.listHelp}>Only active branches with coordinates are shown to Requesters.</Text></View><Text style={styles.total}>{refreshing?'Refreshing…':`${branches.length} total`}</Text></View>
    {error?<View style={styles.empty}><Text style={styles.noticeText}>{error}</Text><TouchableOpacity onPress={()=>refresh({force:true})}><Text style={styles.retry}>Try again</Text></TouchableOpacity></View>:loading&&!data?<View style={styles.grid}>{[1,2,3].map((key)=><CardSkeleton key={key} style={styles.skeleton}/>)}</View>:branches.length===0?<View style={styles.empty}><Text style={styles.emptyTitle}>No branches yet</Text></View>:<View style={styles.grid}>{branches.map((branch)=><View key={branch.id} style={styles.branchCard}><View style={styles.row}><View><Text style={styles.branchName}>{branch.name}</Text><Text style={styles.code}>{branch.code}</Text></View><StatusBadge status={branch.status}/></View><Text style={styles.location}>{branch.address}, {branch.barangay}, {branch.city}</Text><Text style={styles.coordinates}>{branch.latitude == null?'Location pin required':`${branch.latitude.toFixed(5)}, ${branch.longitude.toFixed(5)}`}</Text><Text style={styles.manager}>Managers: {branch.managers?.length?branch.managers.map((manager)=>`${manager.firstName} ${manager.lastName}`.trim()||manager.email).join(', '):'Unassigned'}</Text><View style={styles.actions}><TouchableOpacity style={styles.secondary} onPress={()=>edit(branch)}><Text style={styles.secondaryText}>Edit</Text></TouchableOpacity><TouchableOpacity disabled={saving} style={[styles.secondary,branch.status==='active'&&styles.danger]} onPress={()=>toggle(branch)}><Text style={[styles.secondaryText,branch.status==='active'&&styles.dangerText]}>{branch.status==='active'?'Deactivate':'Activate'}</Text></TouchableOpacity></View></View>)}</View>}
  </AdminShell>;
}

const createStyles = (colors) => StyleSheet.create({formCard:{marginTop:18,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:16,padding:20,marginBottom:18,...BLUETAP_LAYOUT.shadow},eyebrow:{color:colors.primary,fontSize:10,fontWeight:'900',letterSpacing:.8},cardTitle:{color:colors.textPrimary,fontSize:19,fontWeight:'900',marginTop:4},help:{color:colors.textSecondary,fontSize:13,lineHeight:19,marginTop:5,marginBottom:16},fields:{flexDirection:'row',flexWrap:'wrap',gap:12},field:{minWidth:180,flex:1},label:{color:colors.textSecondary,fontSize:12,fontWeight:'800',marginBottom:6},input:{minHeight:46,borderWidth:1,borderColor:colors.inputBorder,backgroundColor:colors.input,borderRadius:10,paddingHorizontal:12,color:colors.textPrimary,outlineStyle:'none'},disabled:{backgroundColor:colors.neutral,color:colors.disabled},mapLabel:{color:colors.textPrimary,fontSize:13,fontWeight:'900',marginTop:18,marginBottom:8},actions:{flexDirection:'row',flexWrap:'wrap',justifyContent:'flex-end',gap:10,marginTop:16},primary:{minHeight:44,paddingHorizontal:18,borderRadius:10,backgroundColor:colors.primary,justifyContent:'center'},primaryText:{color:'#FFF',fontWeight:'900'},secondary:{minHeight:42,paddingHorizontal:16,borderWidth:1,borderColor:colors.inputBorder,borderRadius:10,justifyContent:'center',backgroundColor:colors.surface},secondaryText:{color:colors.primary,fontWeight:'800'},danger:{borderColor:colors.danger},dangerText:{color:colors.danger},notice:{backgroundColor:colors.primarySoft,borderWidth:1,borderColor:colors.border,padding:12,borderRadius:10,marginBottom:15},noticeText:{color:colors.textPrimary,fontWeight:'700'},listHeader:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12,marginTop:8,marginBottom:12},listTitle:{color:colors.textPrimary,fontSize:17,fontWeight:'900'},listHelp:{color:colors.textSecondary,fontSize:12,marginTop:3},total:{color:colors.primary,fontSize:12,fontWeight:'800',backgroundColor:colors.primarySoft,borderRadius:999,paddingHorizontal:10,paddingVertical:6},grid:{flexDirection:'row',flexWrap:'wrap',gap:14},skeleton:{flexBasis:300,maxWidth:480},branchCard:{flexGrow:1,flexBasis:300,maxWidth:480,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:16,padding:18,...BLUETAP_LAYOUT.shadow},row:{flexDirection:'row',justifyContent:'space-between',gap:12},branchName:{color:colors.textPrimary,fontSize:17,fontWeight:'900'},code:{color:colors.textSecondary,fontSize:12,marginTop:3},location:{color:colors.textSecondary,lineHeight:20,marginTop:14},coordinates:{color:colors.primary,fontSize:12,fontWeight:'800',marginTop:5},manager:{color:colors.textPrimary,fontWeight:'700',marginTop:12},empty:{alignItems:'center',padding:34,borderWidth:1,borderStyle:'dashed',borderColor:colors.border,borderRadius:16,backgroundColor:colors.surfaceAlt},emptyTitle:{color:colors.textPrimary,fontSize:17,fontWeight:'900'},retry:{color:colors.primary,fontWeight:'900',marginTop:7}});
