import React from 'react';
import { ActivityIndicator, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, useWindowDimensions, View } from 'react-native';
import AdminShell from '../../components/AdminShell';
import { useAdminRealtimeData } from '../../components/AdminDataProvider';
import { TableSkeleton } from '../../components/AdminSkeleton';
import { useAdminTheme } from '../../components/AdminTheme';
import BlueTapEmptyState from '../../components/BlueTapEmptyState';
import SoftStatusBadge from '../../components/SoftStatusBadge';
import TopToastFeedback from '../../components/TopToastFeedback';
import { getBranches, manageAdminAccount, updateDistributor } from '../../services/branchManagement';
import { ADMIN_CACHE_KEYS, useAdminData } from '../../services/adminDataCache';
import { formatPhilippinePhone } from '../../services/phoneUtils';

const PAGE_SIZE = 10;
const STATUSES = [['pending', 'Pending', 'Applications waiting for review'], ['active', 'Active', 'Approved and available accounts'], ['inactive', 'Inactive', 'Temporarily disabled accounts'], ['rejected', 'Rejected', 'Applications that were declined']];
const SORTS = [['newest', 'Newest'], ['oldest', 'Oldest'], ['name-asc', 'Name A–Z'], ['name-desc', 'Name Z–A']];
const EMPTY = { pending: ['No pending applications', 'New Distributor applications will appear here for Administrator review.'], active: ['No active Distributors', 'Approved Distributors with an authoritative branch assignment will appear here.'], inactive: ['No inactive Distributors', 'Deactivated Distributor accounts will appear here until reactivated.'], rejected: ['No rejected applications', 'Rejected Distributor applications will remain here for reference.'] };
const statusOf = (item) => { const value = String(item?.approvalStatus || item?.distributorStatus || 'pending').toLowerCase(); return value === 'approved' ? 'active' : value; };
const statusLabel = (item) => STATUSES.find(([value]) => value === statusOf(item))?.[1] || statusOf(item);
const branchName = (item) => statusOf(item) === 'pending' ? item.requestedBranchName || 'No branch selected' : item.branchName || 'Branch assignment required';
const branchId = (item) => ['pending', 'rejected'].includes(statusOf(item)) ? item.requestedBranchId : item.branchId;
const timeOf = (value) => { if (!value) return 0; if (typeof value.toDate === 'function') return value.toDate().getTime(); if (Number.isFinite(value.seconds)) return value.seconds * 1000; const parsed = new Date(value).getTime(); return Number.isFinite(parsed) ? parsed : 0; };
const dateText = (value, fallback = 'Not recorded') => { const time = timeOf(value); return time ? new Date(time).toLocaleString([], { year: 'numeric', month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }) : fallback; };
const phoneText = (value) => value ? formatPhilippinePhone(value) || String(value) : 'Not provided';
const publicUidText = (item) => item.publicUid || 'Not assigned';

function Action({ label, tone = 'neutral', disabled, onPress, styles }) { return <Pressable accessibilityRole="button" accessibilityLabel={label} disabled={disabled} onPress={onPress} style={({ hovered, focused, pressed }) => [styles.action, styles[`action${tone}`], (hovered || focused) && styles.hovered, pressed && styles.pressed, disabled && styles.disabled]}><Text style={[styles.actionText, styles[`actionText${tone}`]]}>{label}</Text></Pressable>; }
function Choice({ label, selected, onPress, styles }) { return <Pressable accessibilityRole="button" accessibilityState={{ selected }} onPress={onPress} style={({ hovered, focused, pressed }) => [styles.choice, selected && styles.choiceSelected, (hovered || focused) && styles.hovered, pressed && styles.pressed]}><Text style={[styles.choiceText, selected && styles.choiceTextSelected]}>{label}</Text></Pressable>; }
function Field({ label, value, styles }) { return <View style={styles.field}><Text style={styles.fieldLabel}>{label}</Text><Text selectable style={styles.fieldValue}>{value || 'Not recorded'}</Text></View>; }
function RowActions({ item, busy, onView, onEdit, onApprove, onAction, styles }) {
  const status = statusOf(item);
  return <View style={styles.actions}><Action label="View" disabled={busy} onPress={() => onView(item)} styles={styles} />{status === 'pending' && <><Action label="Approve" tone="success" disabled={busy} onPress={() => onApprove(item)} styles={styles} /><Action label="Reject" tone="danger" disabled={busy} onPress={() => onAction(item, 'reject')} styles={styles} /></>}{status === 'active' && <><Action label="Edit" tone="primary" disabled={busy} onPress={() => onEdit(item)} styles={styles} /><Action label="Deactivate" tone="danger" disabled={busy} onPress={() => onAction(item, 'deactivate')} styles={styles} /></>}{status === 'inactive' && <><Action label="Edit" tone="primary" disabled={busy} onPress={() => onEdit(item)} styles={styles} /><Action label="Reactivate" tone="success" disabled={busy} onPress={() => onAction(item, 'reactivate')} styles={styles} /></>}{busy && <ActivityIndicator size="small" />}</View>;
}

export default function DistributorManagement() {
  const { colors, resolvedTheme } = useAdminTheme(); const styles = React.useMemo(() => createStyles(colors), [colors]); const compact = useWindowDimensions().width < 1060;
  const { distributors: items, distributorsLoading, distributorsRefreshing, distributorsError, refreshDistributors } = useAdminRealtimeData();
  const branchState = useAdminData(ADMIN_CACHE_KEYS.branches, getBranches); const branches = React.useMemo(() => (branchState.data || []).filter((branch) => branch.status === 'active'), [branchState.data]);
  const [filter, setFilter] = React.useState('pending'), [query, setQuery] = React.useState(''), [branchFilter, setBranchFilter] = React.useState('all'), [sort, setSort] = React.useState('newest'), [page, setPage] = React.useState(1);
  const [busy, setBusy] = React.useState(''), [actionError, setActionError] = React.useState(''), [approval, setApproval] = React.useState(null), [branchQuery, setBranchQuery] = React.useState(''), [details, setDetails] = React.useState(null), [edit, setEdit] = React.useState(null);
  const [toast, setToast] = React.useState({ visible: false, message: '', type: 'info' });
  const counts = React.useMemo(() => Object.fromEntries(STATUSES.map(([value]) => [value, items.filter((item) => statusOf(item) === value).length])), [items]);
  const filtered = React.useMemo(() => { const needle = query.trim().toLowerCase(); return items.filter((item) => statusOf(item) === filter).filter((item) => branchFilter === 'all' || branchId(item) === branchFilter).filter((item) => !needle || [item.fullName, item.username, item.email, item.publicUid, item.branchName, item.requestedBranchName].filter(Boolean).join(' ').toLowerCase().includes(needle)).sort((left, right) => sort === 'oldest' ? timeOf(left.createdAt) - timeOf(right.createdAt) : sort === 'name-asc' ? String(left.fullName || left.username).localeCompare(String(right.fullName || right.username)) : sort === 'name-desc' ? String(right.fullName || right.username).localeCompare(String(left.fullName || left.username)) : timeOf(right.createdAt) - timeOf(left.createdAt)); }, [branchFilter, filter, items, query, sort]);
  const pages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE)), currentPage = Math.min(page, pages), visible = filtered.slice((currentPage - 1) * PAGE_SIZE, currentPage * PAGE_SIZE);
  const pageNumbers = [...new Set([1, currentPage - 1, currentPage, currentPage + 1, pages].filter((value) => value >= 1 && value <= pages))].sort((left, right) => left - right);
  React.useEffect(() => setPage(1), [branchFilter, filter, query, sort]);
  const notify = (message, type) => setToast({ visible: true, message, type }); const refresh = () => Promise.all([refreshDistributors({ force: true }), branchState.refresh({ force: false })]);
  const act = async (item, action, options = {}) => { const confirmed = !['reject', 'deactivate'].includes(action) || typeof globalThis.confirm !== 'function' || globalThis.confirm(`${action === 'reject' ? 'Reject this Distributor application' : 'Deactivate this Distributor account'}?`); if (!confirmed) return; setBusy(`${item.uid}:${action}`); setActionError(''); try { await updateDistributor(item.uid, action, options); await refreshDistributors({ force: true }); if (action === 'approve') setApproval(null); notify({ approve: 'Distributor approved successfully.', reject: 'Distributor application rejected.', deactivate: 'Distributor account deactivated.', reactivate: 'Distributor account reactivated.' }[action], 'success'); } catch (error) { const message = error.message || 'Unable to update this Distributor.'; setActionError(message); notify(message, 'error'); } finally { setBusy(''); } };
  const openApproval = (item) => { setApproval({ item, branchId: branches.some((branch) => branch.id === item.requestedBranchId) ? item.requestedBranchId : '' }); setBranchQuery(''); }; const openEdit = (item) => setEdit({ item, fullName: item.fullName || '', email: item.email || '', branchId: item.branchId || '' });
  const saveEdit = async () => { if (!edit?.fullName.trim() || !edit?.email.trim() || !edit?.branchId) return; setBusy(`${edit.item.uid}:edit`); setActionError(''); try { await manageAdminAccount(edit.item.uid, 'updateAccount', { fullName: edit.fullName.trim(), email: edit.email.trim(), role: 'distributor', branchId: edit.branchId, active: statusOf(edit.item) === 'active' }); await refreshDistributors({ force: true }); setEdit(null); notify('Distributor account changes saved and audited.', 'success'); } catch (error) { const message = error.message || 'Unable to save this Distributor.'; setActionError(message); notify(message, 'error'); } finally { setBusy(''); } };
  const branchChoices = branches.filter((branch) => `${branch.name} ${branch.code || ''}`.toLowerCase().includes(branchQuery.trim().toLowerCase())); const loadError = actionError || distributorsError || branchState.error; const resetFilters = () => { setQuery(''); setBranchFilter('all'); }; const actions = (item) => <RowActions item={item} busy={busy.startsWith(`${item.uid}:`)} onView={setDetails} onEdit={openEdit} onApprove={openApproval} onAction={act} styles={styles} />;
  return <AdminShell title="Distributor Management" subtitle="Review applications and manage authorized Distributor accounts.">
    <TopToastFeedback visible={toast.visible} message={toast.message} type={toast.type} onDismiss={() => setToast((value) => ({ ...value, visible: false }))} />
    <View style={styles.summaryGrid}>{STATUSES.map(([value, label, help]) => <Pressable key={value} accessibilityRole="tab" accessibilityState={{ selected: filter === value }} onPress={() => setFilter(value)} style={({ hovered, focused, pressed }) => [styles.summary, filter === value && styles.summarySelected, (hovered || focused) && styles.hovered, pressed && styles.pressed]}><View style={styles.summaryTop}><Text style={[styles.summaryLabel, filter === value && styles.selectedText]}>{label}</Text><Text style={[styles.summaryCount, filter === value && styles.selectedText]}>{counts[value]}</Text></View><Text style={styles.summaryHelp}>{help}</Text></Pressable>)}</View>
    <View style={styles.card}><View style={styles.toolbar}><View style={styles.searchWrap}><Text style={styles.controlLabel}>Search distributors</Text><View style={styles.searchRow}><TextInput accessibilityLabel="Search distributors" value={query} onChangeText={setQuery} placeholder="Name, username, email, public UID, or branch" placeholderTextColor={colors.textSecondary} style={styles.input} />{!!query && <Action label="Clear" onPress={() => setQuery('')} styles={styles} />}</View></View><View style={styles.sortWrap}><Text style={styles.controlLabel}>Sort</Text><View style={styles.choiceRow}>{SORTS.map(([value, label]) => <Choice key={value} label={label} selected={sort === value} onPress={() => setSort(value)} styles={styles} />)}</View></View></View>
      {!!branches.length && <View style={styles.branchFilters}><Text style={styles.controlLabel}>Branch</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.choiceRow}><Choice label="All branches" selected={branchFilter === 'all'} onPress={() => setBranchFilter('all')} styles={styles} />{branches.map((branch) => <Choice key={branch.id} label={branch.name} selected={branchFilter === branch.id} onPress={() => setBranchFilter(branch.id)} styles={styles} />)}</ScrollView></View>}
      <View style={styles.results}><Text style={styles.resultText}>{distributorsRefreshing ? 'Refreshing Distributors…' : filtered.length ? `Showing ${(currentPage - 1) * PAGE_SIZE + 1}–${Math.min(currentPage * PAGE_SIZE, filtered.length)} of ${filtered.length} ${filter} Distributor${filtered.length === 1 ? '' : 's'}` : `0 ${filter} Distributors`}</Text>{(query || branchFilter !== 'all') && <Pressable accessibilityRole="button" onPress={resetFilters}><Text style={styles.resetText}>Reset filters</Text></Pressable>}</View>{!!loadError && <View style={styles.error}><Text style={styles.errorText}>{loadError}</Text><Pressable onPress={refresh}><Text style={styles.retryText}>Retry</Text></Pressable></View>}
      {distributorsLoading && !items.length ? <TableSkeleton rows={6} /> : !visible.length ? <BlueTapEmptyState compact variant={filter === 'pending' ? 'applications' : 'people'} title={EMPTY[filter][0]} description={query || branchFilter !== 'all' ? 'No Distributor records match the current search and branch filters.' : EMPTY[filter][1]} actionLabel={query || branchFilter !== 'all' ? 'Clear filters' : undefined} onAction={resetFilters} themeColors={colors} dark={resolvedTheme === 'dark'} /> : compact ? <View style={styles.mobileList}>{visible.map((item) => <View key={item.uid} style={styles.mobileCard}><View style={styles.mobileHeader}><View style={styles.identity}><Text style={styles.name}>{item.fullName || item.username || 'Unnamed Distributor'}</Text><Text style={styles.muted}>{item.username ? `@${item.username}` : item.email}</Text></View><SoftStatusBadge status={statusOf(item)} label={statusLabel(item)} dark={resolvedTheme === 'dark'} /></View><View style={styles.fieldGrid}><Field label="Public UID" value={publicUidText(item)} styles={styles} /><Field label={statusOf(item) === 'pending' ? 'Requested Branch' : 'Branch'} value={branchName(item)} styles={styles} /><Field label="Contact" value={`${item.email || 'Email not provided'} · ${phoneText(item.phone)}`} styles={styles} /><Field label="Registration Date" value={dateText(item.createdAt)} styles={styles} /></View>{actions(item)}</View>)}</View> : <DistributorTable items={visible} actions={actions} dark={resolvedTheme === 'dark'} styles={styles} />}
      {filtered.length > PAGE_SIZE && <View style={styles.pagination}><Action label="Previous" disabled={currentPage === 1} onPress={() => setPage((value) => Math.max(1, value - 1))} styles={styles} />{pageNumbers.map((number, index) => <React.Fragment key={number}>{index > 0 && number - pageNumbers[index - 1] > 1 && <Text style={styles.resultText}>…</Text>}<Choice label={String(number)} selected={currentPage === number} onPress={() => setPage(number)} styles={styles} /></React.Fragment>)}<Action label="Next" disabled={currentPage === pages} onPress={() => setPage((value) => Math.min(pages, value + 1))} styles={styles} /></View>}
    </View><DetailsModal item={details} onClose={() => setDetails(null)} styles={styles} /><ApprovalModal state={approval} setState={setApproval} query={branchQuery} setQuery={setBranchQuery} choices={branchChoices} busy={busy} onApprove={act} colors={colors} styles={styles} /><EditModal state={edit} setState={setEdit} branches={branches} busy={busy} onSave={saveEdit} colors={colors} styles={styles} />
  </AdminShell>;
}

function DistributorTable({ items, actions, dark, styles }) { return <ScrollView horizontal showsHorizontalScrollIndicator><View style={styles.table}><View style={[styles.tableRow, styles.tableHeader]}>{['Distributor', 'Public UID', 'Branch', 'Contact', 'Registration Date', 'Status', 'Actions'].map((heading, index) => <Text key={heading} style={[styles.cell, styles[`col${index}`], styles.headerText]}>{heading}</Text>)}</View>{items.map((item) => <View key={item.uid} style={styles.tableRow}><View style={[styles.cell, styles.col0]}><Text numberOfLines={1} style={styles.name}>{item.fullName || item.username || 'Unnamed Distributor'}</Text><Text numberOfLines={1} style={styles.muted}>{item.username ? `@${item.username}` : 'Username not set'}</Text></View><Text style={[styles.cell, styles.col1, styles.publicUid]}>{publicUidText(item)}</Text><View style={[styles.cell, styles.col2]}><Text numberOfLines={2} style={styles.body}>{branchName(item)}</Text>{statusOf(item) === 'pending' && <Text style={styles.requested}>Requested Branch</Text>}</View><View style={[styles.cell, styles.col3]}><Text numberOfLines={1} style={styles.body}>{item.email || 'Email not provided'}</Text><Text numberOfLines={1} style={styles.muted}>{phoneText(item.phone)}</Text></View><Text style={[styles.cell, styles.col4, styles.body]}>{dateText(item.createdAt)}</Text><View style={[styles.cell, styles.col5]}><SoftStatusBadge status={statusOf(item)} label={statusLabel(item)} dark={dark} /></View><View style={[styles.cell, styles.col6]}>{actions(item)}</View></View>)}</View></ScrollView>; }
function Section({ title, children, styles }) { return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{children}</View>; }
function DetailsModal({ item, onClose, styles }) { return <Modal visible={!!item} transparent animationType="fade" onRequestClose={onClose}><View style={styles.backdrop}><View accessibilityViewIsModal style={styles.modal}><View style={styles.modalHeading}><View><Text style={styles.modalTitle}>Distributor details</Text><Text style={styles.muted}>{item?.fullName || item?.username || 'Distributor account'}</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Close details" onPress={onClose} style={styles.close}><Text style={styles.closeText}>×</Text></Pressable></View><ScrollView contentContainerStyle={styles.modalContent}><Section title="ACCOUNT" styles={styles}><Field label="Name" value={item?.fullName} styles={styles} /><Field label="Username" value={item?.username ? `@${item.username}` : 'Not assigned'} styles={styles} /><Field label="Public UID" value={item ? publicUidText(item) : ''} styles={styles} /><Field label="Email" value={item?.email || 'Not provided'} styles={styles} /><Field label="Phone" value={phoneText(item?.phone)} styles={styles} /><Field label="Status" value={item ? statusLabel(item) : ''} styles={styles} /></Section><Section title="BRANCH" styles={styles}><Field label={statusOf(item) === 'pending' ? 'Requested Branch' : 'Assigned Branch'} value={item ? branchName(item) : ''} styles={styles} />{statusOf(item) !== 'pending' && item?.requestedBranchName && <Field label="Originally Requested" value={item.requestedBranchName} styles={styles} />}</Section><Section title="REGISTRATION" styles={styles}><Field label="Registered" value={dateText(item?.createdAt)} styles={styles} /><Field label="Email Verification" value={item?.emailVerified ? 'Verified' : 'Not verified'} styles={styles} /><Field label="Face Verification" value={String(item?.faceVerification || 'pending').replaceAll('_', ' ')} styles={styles} /></Section><Section title="ADMIN HISTORY" styles={styles}><Field label="Approved" value={dateText(item?.approvedAt, 'Not approved')} styles={styles} /><Field label="Rejected" value={dateText(item?.rejectedAt, 'Not rejected')} styles={styles} /><Field label="Last Administrative Update" value={dateText(item?.updatedAt)} styles={styles} />{!!item?.rejectionReason && <Field label="Rejection Reason" value={item.rejectionReason} styles={styles} />}</Section></ScrollView><View style={styles.footer}><Action label="Close" onPress={onClose} styles={styles} /></View></View></View></Modal>; }
function BranchOptions({ choices, selected, onSelect, styles }) { return <ScrollView style={styles.branchList} nestedScrollEnabled>{choices.map((branch) => <Pressable key={branch.id} accessibilityRole="radio" accessibilityState={{ checked: selected === branch.id }} onPress={() => onSelect(branch.id)} style={({ hovered, focused }) => [styles.branchOption, selected === branch.id && styles.branchSelected, (hovered || focused) && styles.hovered]}><Text style={styles.branchName}>{branch.name}</Text><Text style={styles.muted}>{branch.code || 'Active branch'}</Text></Pressable>)}{!choices.length && <Text style={styles.inlineEmpty}>No active branches match.</Text>}</ScrollView>; }
function ApprovalModal({ state, setState, query, setQuery, choices, busy, onApprove, colors, styles }) { return <Modal visible={!!state} transparent animationType="fade" onRequestClose={() => setState(null)}><View style={styles.backdrop}><View accessibilityViewIsModal style={styles.modal}><Text style={styles.modalTitle}>Assign branch and approve</Text><Text style={styles.modalCopy}>Approve {state?.item?.fullName || 'this Distributor'} for an active BlueTap branch. The requested branch is selected when it remains active.</Text><TextInput accessibilityLabel="Search active branches" value={query} onChangeText={setQuery} placeholder="Search active branches" placeholderTextColor={colors.textSecondary} style={styles.input} /><BranchOptions choices={choices} selected={state?.branchId} onSelect={(value) => setState((current) => ({ ...current, branchId: value }))} styles={styles} /><View style={styles.footer}><Action label="Cancel" onPress={() => setState(null)} styles={styles} /><Action label={busy ? 'Approving…' : 'Confirm approval'} tone="success" disabled={!state?.branchId || !!busy} onPress={() => onApprove(state.item, 'approve', { branchId: state.branchId })} styles={styles} /></View></View></View></Modal>; }
function EditModal({ state, setState, branches, busy, onSave, colors, styles }) { return <Modal visible={!!state} transparent animationType="fade" onRequestClose={() => setState(null)}><View style={styles.backdrop}><View accessibilityViewIsModal style={styles.modal}><Text style={styles.modalTitle}>Edit Distributor</Text><Text style={styles.modalCopy}>Changes use the protected Admin account workflow and are recorded in the audit log.</Text><Text style={styles.inputLabel}>Full name</Text><TextInput accessibilityLabel="Distributor full name" value={state?.fullName || ''} onChangeText={(value) => setState((current) => ({ ...current, fullName: value }))} placeholderTextColor={colors.textSecondary} style={styles.input} /><Text style={styles.inputLabel}>Email</Text><TextInput accessibilityLabel="Distributor email" value={state?.email || ''} onChangeText={(value) => setState((current) => ({ ...current, email: value }))} autoCapitalize="none" keyboardType="email-address" placeholderTextColor={colors.textSecondary} style={styles.input} /><Text style={styles.inputLabel}>Assigned branch</Text><BranchOptions choices={branches} selected={state?.branchId} onSelect={(value) => setState((current) => ({ ...current, branchId: value }))} styles={styles} /><View style={styles.footer}><Action label="Cancel" onPress={() => setState(null)} styles={styles} /><Action label={busy ? 'Saving…' : 'Save changes'} tone="primary" disabled={!state?.fullName.trim() || !state?.email.trim() || !state?.branchId || !!busy} onPress={onSave} styles={styles} /></View></View></View></Modal>; }

const createStyles = (colors) => StyleSheet.create({
  summaryGrid:{flexDirection:'row',flexWrap:'wrap',gap:12,marginBottom:16},summary:{flexGrow:1,flexBasis:190,minHeight:104,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:16,padding:16,justifyContent:'space-between'},summarySelected:{backgroundColor:colors.primarySoft,borderColor:colors.primary,borderWidth:2},summaryTop:{flexDirection:'row',justifyContent:'space-between',gap:12},summaryLabel:{color:colors.textPrimary,fontSize:15,fontWeight:'900'},summaryCount:{color:colors.textPrimary,fontSize:25,fontWeight:'900'},selectedText:{color:colors.primary},summaryHelp:{color:colors.textSecondary,fontSize:12,lineHeight:17,marginTop:10},
  card:{backgroundColor:colors.surface,borderRadius:18,padding:20,borderWidth:1,borderColor:colors.border},toolbar:{flexDirection:'row',flexWrap:'wrap',gap:16,alignItems:'flex-end'},searchWrap:{flexGrow:1,flexBasis:320,minWidth:0},sortWrap:{flexGrow:1,flexBasis:370},controlLabel:{color:colors.textPrimary,fontSize:12,fontWeight:'900',marginBottom:7},searchRow:{flexDirection:'row',gap:8},input:{flex:1,minWidth:0,minHeight:44,borderWidth:1,borderColor:colors.inputBorder,borderRadius:10,paddingHorizontal:12,color:colors.textPrimary,backgroundColor:colors.input,outlineStyle:'none'},choiceRow:{flexDirection:'row',flexWrap:'wrap',gap:7},choice:{minHeight:40,justifyContent:'center',paddingHorizontal:11,borderRadius:9,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surfaceAlt},choiceSelected:{backgroundColor:colors.primary,borderColor:colors.primary},choiceText:{color:colors.textSecondary,fontSize:12,fontWeight:'800'},choiceTextSelected:{color:'#FFF'},hovered:{borderColor:colors.primary},pressed:{opacity:.82},branchFilters:{marginTop:16},results:{minHeight:50,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12,borderBottomWidth:1,borderBottomColor:colors.border},resultText:{color:colors.textSecondary,fontSize:13,fontWeight:'700'},resetText:{color:colors.primary,fontSize:12,fontWeight:'900'},error:{borderWidth:1,borderColor:colors.danger,backgroundColor:colors.dangerSoft,borderRadius:10,padding:12,marginVertical:10},errorText:{color:colors.danger,fontWeight:'700'},retryText:{color:colors.primary,fontWeight:'900',marginTop:7},
  table:{minWidth:1160},tableRow:{minHeight:86,flexDirection:'row',alignItems:'center',borderBottomWidth:1,borderBottomColor:colors.border},tableHeader:{minHeight:48,backgroundColor:colors.surfaceAlt},cell:{paddingHorizontal:10},col0:{width:180},col1:{width:120},col2:{width:160},col3:{width:210},col4:{width:150},col5:{width:125},col6:{width:215},headerText:{color:colors.textSecondary,fontSize:11,fontWeight:'900',textTransform:'uppercase'},name:{color:colors.textPrimary,fontSize:14,fontWeight:'900'},muted:{color:colors.textSecondary,fontSize:12,marginTop:3},body:{color:colors.textPrimary,fontSize:12,lineHeight:17},publicUid:{color:colors.primary,fontSize:12,fontWeight:'900'},requested:{color:colors.warning,fontSize:10,fontWeight:'900',marginTop:4,textTransform:'uppercase'},actions:{flexDirection:'row',flexWrap:'wrap',alignItems:'center',gap:6},action:{minHeight:36,justifyContent:'center',alignItems:'center',borderRadius:8,borderWidth:1,borderColor:colors.border,paddingHorizontal:10,backgroundColor:colors.surfaceAlt},actionprimary:{backgroundColor:colors.primary,borderColor:colors.primary},actionsuccess:{backgroundColor:colors.success,borderColor:colors.success},actiondanger:{backgroundColor:colors.dangerSoft,borderColor:colors.danger},actionText:{color:colors.textPrimary,fontSize:11,fontWeight:'900'},actionTextprimary:{color:'#FFF'},actionTextsuccess:{color:'#FFF'},actionTextdanger:{color:colors.danger},disabled:{opacity:.5},
  mobileList:{gap:12,marginTop:14},mobileCard:{borderWidth:1,borderColor:colors.border,backgroundColor:colors.surfaceAlt,borderRadius:14,padding:15},mobileHeader:{flexDirection:'row',alignItems:'flex-start',justifyContent:'space-between',gap:12},identity:{flex:1,minWidth:0},fieldGrid:{flexDirection:'row',flexWrap:'wrap',gap:12,marginVertical:14},field:{flexGrow:1,flexBasis:150,minWidth:0},fieldLabel:{color:colors.textSecondary,fontSize:10,fontWeight:'900',textTransform:'uppercase',marginBottom:4},fieldValue:{color:colors.textPrimary,fontSize:13,lineHeight:18,fontWeight:'700'},pagination:{flexDirection:'row',justifyContent:'flex-end',alignItems:'center',gap:12,marginTop:18},backdrop:{flex:1,backgroundColor:colors.overlay,padding:20,justifyContent:'center',alignItems:'center'},modal:{width:'100%',maxWidth:620,maxHeight:'90%',backgroundColor:colors.surface,borderColor:colors.border,borderWidth:1,borderRadius:18,padding:20},modalHeading:{flexDirection:'row',justifyContent:'space-between',gap:12},modalTitle:{color:colors.textPrimary,fontSize:20,fontWeight:'900'},modalCopy:{color:colors.textSecondary,fontSize:13,lineHeight:19,marginTop:7,marginBottom:14},close:{width:36,height:36,borderRadius:9,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surfaceAlt,alignItems:'center',justifyContent:'center'},closeText:{color:colors.textPrimary,fontSize:22},modalContent:{paddingTop:14},section:{borderTopWidth:1,borderTopColor:colors.border,paddingTop:13,marginBottom:13,flexDirection:'row',flexWrap:'wrap',gap:14},sectionTitle:{width:'100%',color:colors.primary,fontSize:11,fontWeight:'900'},inputLabel:{color:colors.textPrimary,fontSize:12,fontWeight:'900',marginBottom:6,marginTop:10},branchList:{maxHeight:240,marginTop:12},branchOption:{borderWidth:1,borderColor:colors.border,borderRadius:10,padding:12,marginBottom:8,backgroundColor:colors.surfaceAlt},branchSelected:{borderColor:colors.primary,backgroundColor:colors.primarySoft,borderWidth:2},branchName:{color:colors.textPrimary,fontWeight:'900'},inlineEmpty:{color:colors.textSecondary,textAlign:'center',padding:18},footer:{flexDirection:'row',justifyContent:'flex-end',gap:9,marginTop:15,paddingTop:14,borderTopWidth:1,borderTopColor:colors.border},
});
