import React from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import AdminShell from '../../components/AdminShell';
import { useAdminTheme } from '../../components/AdminTheme';
import { getDistributors, updateDistributor } from '../../services/branchManagement';

const labels = { pending: 'Pending', active: 'Active', inactive: 'Inactive', rejected: 'Rejected', approved: 'Active' };
export default function DistributorManagement() {
  const { colors } = useAdminTheme(); const styles = createStyles(colors);
  const [items, setItems] = React.useState([]); const [filter, setFilter] = React.useState('pending'); const [query, setQuery] = React.useState(''); const [loading, setLoading] = React.useState(true); const [error, setError] = React.useState(''); const [busy, setBusy] = React.useState('');
  const load = React.useCallback(async () => { setLoading(true); setError(''); try { setItems(await getDistributors()); } catch (e) { setError(e.message || 'Unable to load distributor accounts.'); } finally { setLoading(false); } }, []);
  React.useEffect(() => { load(); }, [load]);
  const act = async (uid, action) => { setBusy(uid + action); try { const updated = await updateDistributor(uid, action); setItems((old) => old.map((item) => item.uid === uid ? updated : item)); } catch (e) { setError(e.message); } finally { setBusy(''); } };
  const visible = items.filter((item) => (filter === 'all' || item.approvalStatus === filter || (filter === 'active' && item.approvalStatus === 'approved')) && `${item.fullName} ${item.username} ${item.email}`.toLowerCase().includes(query.toLowerCase()));
  return <AdminShell title="Distributor Management" subtitle="Review distributor applications and manage approved distributor accounts."><View style={styles.card}><View style={styles.tabs}>{['pending','active','inactive','rejected'].map((value) => <Pressable key={value} onPress={() => setFilter(value)} style={[styles.tab, filter === value && styles.tabActive]}><Text style={[styles.tabText, filter === value && styles.tabTextActive]}>{labels[value]} ({items.filter((x) => x.approvalStatus === value).length})</Text></Pressable>)}</View><TextInput value={query} onChangeText={setQuery} placeholder="Search name, username, or email" placeholderTextColor={colors.textSecondary} style={styles.search} /><Text style={styles.count}>{visible.length} distributor{visible.length === 1 ? '' : 's'}</Text>{loading ? <ActivityIndicator color={colors.primary} /> : error ? <Text style={styles.error}>{error}</Text> : visible.length === 0 ? <Text style={styles.empty}>No {labels[filter].toLowerCase()} distributors.</Text> : visible.map((item) => <View key={item.uid} style={styles.row}><View style={styles.copy}><Text style={styles.name}>{item.fullName || item.username}</Text><Text style={styles.meta}>{item.username} · {item.email}</Text><Text style={styles.meta}>{item.phone || 'No phone'} {item.barangay ? `· ${item.barangay}` : ''}</Text><Text style={styles.badge}>{labels[item.approvalStatus] || item.approvalStatus}</Text></View><View style={styles.actions}>{item.approvalStatus === 'pending' && <><Pressable style={styles.approve} onPress={() => act(item.uid, 'approve')}><Text style={styles.buttonText}>Approve</Text></Pressable><Pressable style={styles.reject} onPress={() => act(item.uid, 'reject')}><Text style={styles.rejectText}>Reject</Text></Pressable></>}{item.approvalStatus === 'active' && <Pressable style={styles.reject} onPress={() => act(item.uid, 'deactivate')}><Text style={styles.rejectText}>Deactivate</Text></Pressable>}{item.approvalStatus === 'inactive' && <Pressable style={styles.approve} onPress={() => act(item.uid, 'reactivate')}><Text style={styles.buttonText}>Reactivate</Text></Pressable>}{busy.startsWith(item.uid) && <ActivityIndicator color={colors.primary} />}</View></View>)}</View></AdminShell>;
}
const createStyles = (colors) => StyleSheet.create({ card:{backgroundColor:colors.surface,borderRadius:16,padding:20,borderWidth:1,borderColor:colors.border},tabs:{flexDirection:'row',flexWrap:'wrap',gap:8,marginBottom:16},tab:{paddingHorizontal:12,paddingVertical:9,borderRadius:9,backgroundColor:colors.surfaceAlt},tabActive:{backgroundColor:colors.primary},tabText:{color:colors.textSecondary,fontWeight:'700'},tabTextActive:{color:'#FFF'},search:{borderWidth:1,borderColor:colors.inputBorder,borderRadius:10,padding:12,color:colors.textPrimary,backgroundColor:colors.input,outlineStyle:'none'},count:{marginVertical:14,color:colors.textSecondary},row:{paddingVertical:15,borderTopWidth:1,borderTopColor:colors.border,flexDirection:'row',gap:12},copy:{flex:1},name:{fontWeight:'800',color:colors.textPrimary,fontSize:16},meta:{color:colors.textSecondary,marginTop:3,fontSize:12},badge:{color:colors.primary,fontWeight:'800',marginTop:7,fontSize:12},actions:{gap:8,alignItems:'flex-end'},approve:{backgroundColor:colors.success,borderRadius:8,paddingHorizontal:12,paddingVertical:9},reject:{borderWidth:1,borderColor:colors.danger,borderRadius:8,paddingHorizontal:12,paddingVertical:9},buttonText:{color:'#FFF',fontWeight:'800'},rejectText:{color:colors.danger,fontWeight:'800'},empty:{color:colors.textSecondary,textAlign:'center',padding:28},error:{color:colors.danger,padding:12} });
