import React from 'react';
import { ActivityIndicator, StyleSheet, Switch, Text, TextInput, TouchableOpacity, View } from 'react-native';
import AdminShell from '../../components/AdminShell';
import { BLUETAP_COLORS, BLUETAP_LAYOUT } from '../../constants/bluetapTheme';
import { createAdminAccount, getAdminCreatedAccounts, getBranches, getManagers, updateManagerAssignment } from '../../services/branchManagement';
import { checkUsername, validateUsername } from '../../services/usernameAuth';

const emptyForm = { fullName: '', email: '', username: '', temporaryPassword: '', confirmPassword: '', role: 'requester', branchId: '', requirePasswordChange: true };
export default function AdminManagersPage() {
  const [form, setForm] = React.useState(emptyForm); const [accounts, setAccounts] = React.useState([]); const [managers, setManagers] = React.useState([]); const [branches, setBranches] = React.useState([]); const [loading, setLoading] = React.useState(true); const [saving, setSaving] = React.useState(false); const [message, setMessage] = React.useState(''); const [showPassword, setShowPassword] = React.useState(false); const [showConfirmPassword, setShowConfirmPassword] = React.useState(false); const [usernameStatus, setUsernameStatus] = React.useState('idle');
  const set = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const load = React.useCallback(async () => { try { const [a, m, b] = await Promise.all([getAdminCreatedAccounts(), getManagers(), getBranches()]); setAccounts(a); setManagers(m); setBranches(b); } catch (error) { setMessage(error.message); } finally { setLoading(false); } }, []);
  React.useEffect(() => { load(); }, [load]);
  const activeBranches = branches.filter((branch) => branch.status === 'active'); const isManager = form.role === 'manager';
  React.useEffect(() => { if (isManager) return setUsernameStatus('idle'); const validation = validateUsername(form.username); if (validation) return setUsernameStatus(form.username ? 'invalid' : 'idle'); let active = true; setUsernameStatus('checking'); const timer = setTimeout(() => checkUsername(form.username).then((result) => active && setUsernameStatus(result.available ? 'available' : 'taken')).catch(() => active && setUsernameStatus('unavailable')), 350); return () => { active = false; clearTimeout(timer); }; }, [form.username, isManager]);
  const create = async () => { if (!isManager && usernameStatus !== 'available') return setMessage('Choose an available username before creating the account.'); if (form.temporaryPassword !== form.confirmPassword) return setMessage('Temporary passwords do not match.'); if (isManager && !form.branchId) return setMessage('Choose an active branch for this Manager.'); setSaving(true); setMessage(''); try { await createAdminAccount({ ...form, email: form.email.trim().toLowerCase(), requirePasswordChange: isManager ? true : form.requirePasswordChange }); setForm(emptyForm); await load(); setMessage('Account created. The user must change their temporary password on first sign-in.'); } catch (error) { setMessage(error.message); } finally { setSaving(false); } };
  const changeManager = async (manager, changes) => { setSaving(true); setMessage(''); try { await updateManagerAssignment(manager.uid, changes); await load(); setMessage(changes.managerStatus === 'inactive' ? 'Manager deactivated.' : 'Manager assignment updated.'); } catch (error) { setMessage(error.message); } finally { setSaving(false); } };
  return <AdminShell title="Accounts & Audit" subtitle="Create and manage BlueTap accounts. Manager access remains limited to one active branch."><View style={styles.card}>
    <Text style={styles.title}>Create new account</Text><Text style={styles.help}>Passwords are stored only by Firebase Authentication and are never shown again.</Text>
    <View style={styles.fieldGrid}>
      <View style={styles.field}><Text style={styles.label}>Full name</Text><TextInput value={form.fullName} onChangeText={(v) => set('fullName', v)} style={styles.input} /></View>
      <View style={styles.field}><Text style={styles.label}>Email</Text><TextInput autoCapitalize="none" keyboardType="email-address" value={form.email} onChangeText={(v) => set('email', v)} style={styles.input} /></View>
      {!isManager && <View style={styles.field}><Text style={styles.label}>Username</Text><TextInput autoCapitalize="none" value={form.username} onChangeText={(v) => set('username', v)} style={styles.input} placeholder="4–20 letters, numbers, or underscores" />{usernameStatus !== 'idle' && <Text style={{ fontSize: 12, marginTop: 5, color: usernameStatus === 'available' ? BLUETAP_COLORS.success : ['taken', 'invalid', 'unavailable'].includes(usernameStatus) ? BLUETAP_COLORS.danger : BLUETAP_COLORS.textSecondary, fontWeight: usernameStatus === 'checking' ? '400' : '700' }}>{usernameStatus === 'checking' ? 'Checking username…' : usernameStatus === 'available' ? '✓ Username is available' : usernameStatus === 'taken' ? 'Username is already taken' : usernameStatus === 'unavailable' ? 'Unable to check username' : validateUsername(form.username)}</Text>}</View>}
      <View style={styles.field}><Text style={styles.label}>Temporary password</Text><View style={{ flexDirection: 'row', alignItems: 'center' }}><TextInput secureTextEntry={!showPassword} value={form.temporaryPassword} onChangeText={(v) => set('temporaryPassword', v)} style={[styles.input, { flex: 1 }]} /><TouchableOpacity accessibilityRole="button" accessibilityLabel={showPassword ? 'Hide temporary password' : 'Show temporary password'} onPress={() => setShowPassword((value) => !value)} style={{ marginLeft: -58, width: 58, minHeight: 46, alignItems: 'center', justifyContent: 'center' }}><Text style={{ color: BLUETAP_COLORS.primary, fontWeight: '800', fontSize: 12 }}>{showPassword ? 'Hide' : 'Show'}</Text></TouchableOpacity></View><Text style={styles.hint}>Use 12–128 characters with uppercase, lowercase, and a number.</Text></View>
      <View style={styles.field}><Text style={styles.label}>Confirm temporary password</Text><View style={{ flexDirection: 'row', alignItems: 'center' }}><TextInput secureTextEntry={!showConfirmPassword} value={form.confirmPassword} onChangeText={(v) => set('confirmPassword', v)} style={[styles.input, { flex: 1 }]} /><TouchableOpacity accessibilityRole="button" accessibilityLabel={showConfirmPassword ? 'Hide confirmation password' : 'Show confirmation password'} onPress={() => setShowConfirmPassword((value) => !value)} style={{ marginLeft: -58, width: 58, minHeight: 46, alignItems: 'center', justifyContent: 'center' }}><Text style={{ color: BLUETAP_COLORS.primary, fontWeight: '800', fontSize: 12 }}>{showConfirmPassword ? 'Hide' : 'Show'}</Text></TouchableOpacity></View></View>
    </View>
    <Text style={styles.label}>Role</Text><View style={styles.choices}>{['requester', 'distributor', 'manager'].map((role) => <TouchableOpacity key={role} onPress={() => setForm((current) => ({ ...current, role, branchId: role === 'manager' ? current.branchId : '' }))} style={[styles.choice, form.role === role && styles.selected]}><Text style={[styles.choiceText, form.role === role && styles.selectedText]}>{role}</Text></TouchableOpacity>)}</View>
    {isManager && <><Text style={styles.label}>Active branch</Text><View style={styles.choices}>{activeBranches.map((branch) => <TouchableOpacity key={branch.id} onPress={() => set('branchId', branch.id)} style={[styles.choice, form.branchId === branch.id && styles.selected]}><Text style={[styles.choiceText, form.branchId === branch.id && styles.selectedText]}>{branch.name} ({branch.code})</Text></TouchableOpacity>)}</View></>}
    <View style={styles.toggle}><Switch value={isManager ? true : form.requirePasswordChange} disabled={isManager} onValueChange={(v) => set('requirePasswordChange', v)} /><Text style={styles.toggleText}>Require password change on first sign-in{isManager ? ' (required for Managers)' : ''}</Text></View>
    <TouchableOpacity disabled={saving} onPress={create} style={[styles.primary, saving && styles.disabled]}><Text style={styles.primaryText}>{saving ? 'Creating...' : 'Create account'}</Text></TouchableOpacity>
  </View>{!!message && <View accessibilityRole="alert" style={[styles.notice, /created|updated|deactivated/i.test(message) && styles.noticeSuccess]}><Text style={[styles.message, /created|updated|deactivated/i.test(message) && styles.messageSuccess]}>{message}</Text></View>}
  {loading ? <ActivityIndicator color={BLUETAP_COLORS.primary} /> : <View style={styles.list}><Text style={styles.section}>Existing accounts</Text><Text style={styles.sectionHelp}>Accounts provisioned through the Admin workspace.</Text>{accounts.length === 0 && <Text style={styles.empty}>No manually-created accounts yet.</Text>}{accounts.map((account) => <View key={account.uid} style={styles.row}><View style={styles.rowHeader}><Text style={styles.name}>{account.fullName || account.email}</Text><Text style={styles.roleBadge}>{account.role}</Text></View><Text style={styles.detail}>{account.email}{account.username ? ` · @${account.username}` : ''}</Text><Text style={styles.detail}>{account.branchName ? `Branch: ${account.branchName} · ` : ''}{account.mustChangePassword ? 'Password change required' : 'Password set'} · {account.status}</Text></View>)}<Text style={styles.section}>Managers</Text><Text style={styles.sectionHelp}>Assign each Manager to one active branch.</Text>{managers.length === 0 && <Text style={styles.empty}>No Manager accounts yet.</Text>}{managers.map((manager) => <View key={manager.uid} style={styles.row}><View style={styles.rowHeader}><Text style={styles.name}>{`${manager.firstName} ${manager.lastName}`.trim() || manager.email}</Text><Text style={styles.roleBadge}>manager</Text></View><Text style={styles.detail}>{manager.email} · {manager.branch?.name || 'Unassigned'} · {manager.managerStatus}</Text><View style={styles.choices}>{activeBranches.map((branch) => branch.id !== manager.branchId && <TouchableOpacity key={branch.id} disabled={saving} onPress={() => changeManager(manager, { branchId: branch.id, managerStatus: 'active' })} style={styles.small}><Text style={styles.smallText}>Assign {branch.code}</Text></TouchableOpacity>)}{manager.managerStatus === 'active' ? <TouchableOpacity disabled={saving} onPress={() => changeManager(manager, { managerStatus: 'inactive' })} style={styles.small}><Text style={styles.smallText}>Deactivate</Text></TouchableOpacity> : <TouchableOpacity disabled={saving || !manager.branchId} onPress={() => changeManager(manager, { branchId: manager.branchId, managerStatus: 'active' })} style={styles.small}><Text style={styles.smallText}>Reactivate</Text></TouchableOpacity>}</View></View>)}</View>}</AdminShell>;
}
const styles = StyleSheet.create({ card:{maxWidth:760,backgroundColor:BLUETAP_COLORS.surface,borderWidth:1,borderColor:BLUETAP_COLORS.border,borderRadius:16,padding:20,marginBottom:16,...BLUETAP_LAYOUT.shadow},title:{fontSize:18,fontWeight:'800',color:BLUETAP_COLORS.textPrimary},help:{color:BLUETAP_COLORS.textSecondary,marginTop:6},hint:{color:BLUETAP_COLORS.textSecondary,fontSize:12,marginTop:5},fieldGrid:{flexDirection:'row',flexWrap:'wrap',gap:12},field:{flexGrow:1,flexBasis:270},label:{fontSize:12,fontWeight:'700',color:'#38566E',marginTop:12,marginBottom:6},input:{minHeight:46,borderWidth:1,borderColor:'#BDD5E6',backgroundColor:BLUETAP_COLORS.surfaceAlt,borderRadius:10,paddingHorizontal:12,color:BLUETAP_COLORS.textPrimary,outlineStyle:'none'},choices:{flexDirection:'row',flexWrap:'wrap',gap:8},choice:{borderWidth:1,borderColor:'#B9D3E6',backgroundColor:'#FFF',borderRadius:20,paddingHorizontal:13,paddingVertical:9},selected:{backgroundColor:BLUETAP_COLORS.primary,borderColor:BLUETAP_COLORS.primary},choiceText:{color:'#365D78',fontWeight:'700',textTransform:'capitalize'},selectedText:{color:'#FFF'},toggle:{flexDirection:'row',alignItems:'center',gap:10,marginTop:16},toggleText:{color:'#38566E',fontWeight:'600'},primary:{backgroundColor:BLUETAP_COLORS.primary,borderRadius:10,minHeight:46,alignItems:'center',justifyContent:'center',marginTop:16},primaryText:{color:'#FFF',fontWeight:'800'},disabled:{opacity:.5},notice:{maxWidth:760,backgroundColor:'#FFF5F4',borderWidth:1,borderColor:'#F1C5C2',borderRadius:10,padding:12,marginBottom:14},noticeSuccess:{backgroundColor:'#EFFAF4',borderColor:'#BDE6CF'},message:{color:BLUETAP_COLORS.danger,fontWeight:'700'},messageSuccess:{color:BLUETAP_COLORS.success},list:{maxWidth:900,gap:10},section:{fontSize:17,fontWeight:'800',color:BLUETAP_COLORS.textPrimary,marginTop:8},sectionHelp:{color:BLUETAP_COLORS.textSecondary,fontSize:12,marginTop:-4,marginBottom:3},row:{backgroundColor:BLUETAP_COLORS.surface,borderWidth:1,borderColor:BLUETAP_COLORS.border,borderRadius:12,padding:14},rowHeader:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10},name:{flex:1,color:BLUETAP_COLORS.textPrimary,fontWeight:'800'},roleBadge:{color:BLUETAP_COLORS.primary,backgroundColor:BLUETAP_COLORS.primarySoft,borderRadius:999,paddingHorizontal:9,paddingVertical:4,fontSize:11,fontWeight:'800',textTransform:'capitalize'},detail:{color:BLUETAP_COLORS.textSecondary,marginTop:4},small:{borderWidth:1,borderColor:'#8DBADD',backgroundColor:'#FFF',borderRadius:9,paddingHorizontal:9,paddingVertical:7},smallText:{color:BLUETAP_COLORS.primary,fontSize:12,fontWeight:'700'},empty:{color:BLUETAP_COLORS.textSecondary,backgroundColor:BLUETAP_COLORS.surfaceAlt,borderWidth:1,borderStyle:'dashed',borderColor:BLUETAP_COLORS.border,borderRadius:12,padding:18} });
