import React from 'react';
import { ActivityIndicator, StyleSheet, Switch, Text, TextInput, TouchableOpacity, View } from 'react-native';
import AdminShell from '../../components/AdminShell';
import { SectionCard, StatusBadge } from '../../components/DashboardUi';
import { BLUETAP_COLORS } from '../../constants/bluetapTheme';
import { getRegistrationSecurity, updateRegistrationSecurity } from '../../services/adminRegistrationSecurity';

export default function RegistrationSecurityPage() {
  const [settings, setSettings] = React.useState(null); const [message, setMessage] = React.useState(''); const [isError, setIsError] = React.useState(false); const [saving, setSaving] = React.useState(false);
  React.useEffect(() => { getRegistrationSecurity().then(setSettings).catch((error) => { setMessage(error.message); setIsError(true); }); }, []);
  const toggle = (key) => { const next = { ...settings, [key]: !settings[key] }; if (!next.faceVerificationEnabled && !next.emailOtpEnabled) { setMessage('At least one registration verification method must remain enabled.'); setIsError(true); return; } setMessage(''); setIsError(false); setSettings(next); };
  const save = async () => { const next = { ...settings, maxAccountsPerDevice: Number(settings.maxAccountsPerDevice), maxAccountsPerIp: Number(settings.maxAccountsPerIp) }; if (![next.maxAccountsPerDevice, next.maxAccountsPerIp].every((value) => Number.isInteger(value) && value >= 1 && value <= 20)) { setMessage('Account limits must be whole numbers from 1 to 20.'); setIsError(true); return; } setSaving(true); setMessage(''); try { setSettings(await updateRegistrationSecurity(next)); setMessage('Registration security settings saved.'); setIsError(false); } catch (error) { setMessage(error.message); setIsError(true); } finally { setSaving(false); } };
  return <AdminShell title="Registration Security" subtitle="Control identity verification and registration abuse safeguards">
    {!settings ? <ActivityIndicator color={BLUETAP_COLORS.primary} /> : <View style={styles.stack}>
      <SectionCard style={styles.summaryCard}><Text style={styles.summaryEyebrow}>POLICY SUMMARY</Text><Text style={styles.title}>Registration protection is active</Text><View style={styles.summaryGrid}><View style={styles.summaryItem}><Text style={styles.summaryLabel}>Face verification</Text><StatusBadge status={settings.faceVerificationEnabled ? 'enabled' : 'disabled'} /></View><View style={styles.summaryItem}><Text style={styles.summaryLabel}>Email OTP</Text><StatusBadge status={settings.emailOtpEnabled ? 'enabled' : 'disabled'} /></View><View style={styles.summaryItem}><Text style={styles.summaryLabel}>Device limit</Text><Text style={styles.summaryValue}>{settings.maxAccountsPerDevice}</Text></View><View style={styles.summaryItem}><Text style={styles.summaryLabel}>Network/IP limit</Text><Text style={styles.summaryValue}>{settings.maxAccountsPerIp}</Text></View></View></SectionCard>
      <SectionCard><Text style={styles.title}>Verification methods</Text><Text style={styles.help}>At least one method must stay enabled so new accounts can be verified.</Text>{[['faceVerificationEnabled','Face verification','Confirm a registrant is physically present.'],['emailOtpEnabled','Email OTP verification','Confirm access to the submitted email address.']].map(([key,label,help]) => <View style={styles.setting} key={key}><View style={styles.settingCopy}><Text style={styles.label}>{label}</Text><Text style={styles.help}>{help}</Text></View><Switch trackColor={{ false:'#C8D5DF', true:'#8EC9F2' }} thumbColor={settings[key] ? BLUETAP_COLORS.primary : '#FFF'} value={settings[key]} onValueChange={() => toggle(key)} /></View>)}</SectionCard>
      <SectionCard><Text style={styles.title}>Account limits</Text><Text style={styles.help}>Limit registrations from a single device or network. Use whole numbers from 1 to 20.</Text><View style={styles.fields}>{[['maxAccountsPerDevice','Maximum accounts per device'],['maxAccountsPerIp','Maximum accounts per network/IP']].map(([key,label]) => <View key={key} style={styles.field}><Text style={styles.inputLabel}>{label}</Text><TextInput accessibilityLabel={label} keyboardType="number-pad" value={String(settings[key])} onChangeText={(value) => setSettings({ ...settings, [key]: value })} style={styles.input} /></View>)}</View></SectionCard>
      {!!message && <View accessibilityRole="alert" style={[styles.notice, isError ? styles.errorNotice : styles.successNotice]}><Text style={[styles.noticeText, isError ? styles.errorText : styles.successText]}>{message}</Text></View>}
      <TouchableOpacity disabled={saving} onPress={save} style={[styles.button, saving && styles.disabled]}><Text style={styles.buttonText}>{saving ? 'Saving…' : 'Save changes'}</Text></TouchableOpacity>
    </View>}
  </AdminShell>;
}
const styles = StyleSheet.create({ stack:{maxWidth:820,gap:16},summaryCard:{backgroundColor:'#F0F8FF'},summaryEyebrow:{color:BLUETAP_COLORS.primary,fontSize:10,fontWeight:'900',letterSpacing:.8,marginBottom:6},summaryGrid:{flexDirection:'row',flexWrap:'wrap',gap:10,marginTop:18},summaryItem:{flexGrow:1,flexBasis:150,backgroundColor:'#FFF',borderWidth:1,borderColor:BLUETAP_COLORS.border,borderRadius:12,padding:12},summaryLabel:{color:BLUETAP_COLORS.textSecondary,fontSize:11,fontWeight:'800',marginBottom:8},summaryValue:{color:BLUETAP_COLORS.textPrimary,fontSize:21,fontWeight:'900'},title:{color:BLUETAP_COLORS.textPrimary,fontSize:18,fontWeight:'800'},help:{color:BLUETAP_COLORS.textSecondary,fontSize:13,lineHeight:19,marginTop:5},setting:{minHeight:72,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:20,borderTopWidth:1,borderTopColor:BLUETAP_COLORS.border,marginTop:16,paddingTop:16},settingCopy:{flex:1},label:{color:BLUETAP_COLORS.textPrimary,fontWeight:'800'},fields:{flexDirection:'row',flexWrap:'wrap',gap:14,marginTop:18},field:{flexGrow:1,flexBasis:230},inputLabel:{color:'#38566E',fontSize:12,fontWeight:'700',marginBottom:7},input:{minHeight:46,borderWidth:1,borderColor:'#BDD5E6',backgroundColor:'#F8FCFF',borderRadius:10,paddingHorizontal:12,color:BLUETAP_COLORS.textPrimary,outlineStyle:'none'},notice:{borderRadius:12,padding:14,borderWidth:1},errorNotice:{backgroundColor:'#FFF5F4',borderColor:'#F1C5C2'},successNotice:{backgroundColor:'#EFFAF4',borderColor:'#BDE6CF'},noticeText:{fontWeight:'700'},errorText:{color:BLUETAP_COLORS.danger},successText:{color:BLUETAP_COLORS.success},button:{alignSelf:'flex-start',minHeight:46,paddingHorizontal:22,alignItems:'center',justifyContent:'center',backgroundColor:BLUETAP_COLORS.primary,borderRadius:10},buttonText:{color:'#FFF',fontWeight:'800'},disabled:{opacity:.55} });
