import React from 'react';
import { Animated, Image, Pressable, ScrollView, StyleSheet, Text, TouchableOpacity, useWindowDimensions, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { usePathname, useRouter } from 'expo-router';
import { BLUETAP_COLORS } from '../constants/bluetapTheme';
import { signOutAndClearSessions } from '../services/authSession';
const links=[['D','Dashboard','/admin/dashboard'],['B','Branches','/admin/branches'],['A','Accounts & Audit','/admin/managers'],['D','Distributors','/admin/distributors'],['S','Registration Security','/admin/registration-security']];
export default function AdminShell({title,subtitle,children}) { const router=useRouter(), pathname=usePathname(), compact=useWindowDimensions().width<768; const [open,setOpen]=React.useState(!compact); const slide=React.useRef(new Animated.Value(!compact?1:0)).current; React.useEffect(()=>{setOpen(!compact);Animated.timing(slide,{toValue:!compact?1:0,duration:220,useNativeDriver:true}).start();},[compact]); const toggle=()=>{const next=!open;setOpen(next);Animated.timing(slide,{toValue:next?1:0,duration:220,useNativeDriver:true}).start();}; const width=compact?270:238; const nav=links.map(([i,l,p])=><TouchableOpacity key={p} style={[s.link,pathname===p&&s.active]} onPress={()=>{router.replace(p);if(compact)toggle();}}><Text style={s.icon}>{i}</Text><Text style={s.linkText}>{l}</Text></TouchableOpacity>); const side=<Animated.View style={[s.side,compact&&s.mobile,{width,transform:[{translateX:slide.interpolate({inputRange:[0,1],outputRange:[-width,0]})}]}]}><View style={s.brand}><Image source={require('../assets/icons/bluetapwhitelogo.png')} style={s.logo}/><View><Text style={s.brandText}>BlueTap</Text><Text style={s.role}>Administrator</Text></View></View><View style={s.nav}>{nav}</View><TouchableOpacity style={s.logout} onPress={async()=>{await signOutAndClearSessions();router.replace('/login');}}><Text style={s.linkText}>Logout</Text></TouchableOpacity></Animated.View>; return <SafeAreaView style={s.root}><View style={s.layout}>{!compact&&side}<View style={s.main}><View style={s.top}><TouchableOpacity accessibilityRole="button" accessibilityLabel={open?'Close menu':'Open menu'} onPress={toggle} style={s.menu}><Text style={s.menuText}>{open?'×':'☰'}</Text></TouchableOpacity><View style={s.heading}><Text style={s.title}>{title}</Text>{!!subtitle&&<Text style={s.subtitle}>{subtitle}</Text>}</View></View><ScrollView contentContainerStyle={s.content}>{children}</ScrollView></View>{compact&&<>{open&&<Pressable onPress={toggle} style={s.backdrop}/>} {side}</>}</View></SafeAreaView>; }
const s=StyleSheet.create({root:{flex:1,backgroundColor:BLUETAP_COLORS.background},layout:{flex:1,flexDirection:'row'},side:{backgroundColor:BLUETAP_COLORS.primary,zIndex:3},mobile:{position:'absolute',left:0,top:0,bottom:0,elevation:10,shadowColor:'#12304A',shadowOpacity:.25,shadowRadius:16},brand:{height:82,flexDirection:'row',alignItems:'center',padding:22,borderBottomWidth:1,borderColor:'rgba(255,255,255,.14)'},logo:{width:32,height:32,marginRight:10},brandText:{color:'#FFF',fontWeight:'800',fontSize:19},role:{color:'#CBEAFF',fontSize:12},nav:{padding:14},link:{minHeight:46,flexDirection:'row',alignItems:'center',padding:12,borderRadius:10,marginBottom:5},active:{backgroundColor:'rgba(255,255,255,.18)'},icon:{width:26,color:'#FFF',fontWeight:'900'},linkText:{color:'#FFF',fontWeight:'700'},logout:{marginTop:'auto',padding:22,borderTopWidth:1,borderColor:'rgba(255,255,255,.14)'},main:{flex:1,minWidth:0},top:{minHeight:94,flexDirection:'row',alignItems:'center',paddingHorizontal:24,gap:12},menu:{width:42,height:42,borderRadius:10,alignItems:'center',justifyContent:'center',backgroundColor:BLUETAP_COLORS.primarySoft},menuText:{color:BLUETAP_COLORS.primary,fontSize:25,fontWeight:'800'},heading:{flex:1},title:{fontSize:24,fontWeight:'800',color:BLUETAP_COLORS.textPrimary},subtitle:{fontSize:13,color:BLUETAP_COLORS.textSecondary,marginTop:4},content:{paddingHorizontal:28,paddingBottom:32},backdrop:{position:'absolute',inset:0,zIndex:2,backgroundColor:'rgba(18,48,74,.38)'}});
