import React from 'react';
import { StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { BLUETAP_COLORS, BLUETAP_LAYOUT } from '../constants/bluetapTheme';

export function SectionCard({ children, style }) { return <View style={[dashboardStyles.card, style]}>{children}</View>; }
export function StatusBadge({ status = 'active' }) { const active = status === 'active' || status === 'enabled'; const neutral = status === 'unavailable' || status === 'pending'; return <View style={[styles.badge, active ? styles.active : neutral ? styles.neutral : styles.inactive]}><Text style={[styles.badgeText, active ? styles.activeText : neutral ? styles.neutralText : styles.inactiveText]}>{status}</Text></View>; }
export function StatCard({ label, value, detail, tone = 'blue' }) { return <SectionCard style={styles.statCard}><View style={[styles.statIcon, tone === 'green' && styles.statIconGreen, tone === 'navy' && styles.statIconNavy]}><Text style={styles.statIconText}>{label.charAt(0)}</Text></View><Text style={styles.statLabel}>{label}</Text><Text style={styles.statValue}>{value}</Text>{!!detail && <Text style={styles.statDetail}>{detail}</Text>}</SectionCard>; }
export function EmptyState({ title, detail, style }) { return <View style={[styles.empty, style]}><Text style={styles.emptyTitle}>{title}</Text>{!!detail && <Text style={styles.emptyDetail}>{detail}</Text>}</View>; }
export function PrimaryButton({ children, style, ...props }) { return <TouchableOpacity activeOpacity={0.85} style={[styles.primary, style]} {...props}><Text style={styles.primaryText}>{children}</Text></TouchableOpacity>; }
export function SecondaryButton({ children, style, textStyle, ...props }) { return <TouchableOpacity activeOpacity={0.85} style={[styles.secondary, style]} {...props}><Text style={[styles.secondaryText, textStyle]}>{children}</Text></TouchableOpacity>; }
export const dashboardStyles = StyleSheet.create({ card: { backgroundColor: BLUETAP_COLORS.surface, borderWidth: 1, borderColor: BLUETAP_COLORS.border, borderRadius: BLUETAP_LAYOUT.radius.lg, padding: 20, ...BLUETAP_LAYOUT.shadow }, title: { color: BLUETAP_COLORS.textPrimary, fontSize: 18, fontWeight: '800' }, body: { color: BLUETAP_COLORS.textSecondary, lineHeight: 20 }, label: { color: '#38566E', fontSize: 12, fontWeight: '700', marginBottom: 6 }, input: { minHeight: 46, borderWidth: 1, borderColor: '#BDD5E6', backgroundColor: BLUETAP_COLORS.surfaceAlt, borderRadius: 10, paddingHorizontal: 12, color: BLUETAP_COLORS.textPrimary, outlineStyle: 'none' } });
const styles = StyleSheet.create({ badge: { alignSelf: 'flex-start', borderRadius: 999, paddingHorizontal: 10, paddingVertical: 5 }, badgeText: { fontSize: 12, fontWeight: '800', textTransform: 'capitalize' }, active: { backgroundColor: '#E3F7EC' }, activeText: { color: BLUETAP_COLORS.success }, inactive: { backgroundColor: BLUETAP_COLORS.dangerSoft }, inactiveText: { color: BLUETAP_COLORS.danger }, neutral:{backgroundColor:'#EEF3F7'},neutralText:{color:BLUETAP_COLORS.textSecondary}, primary: { minHeight: 44, paddingHorizontal: 18, alignItems: 'center', justifyContent: 'center', borderRadius: 10, backgroundColor: BLUETAP_COLORS.primary }, primaryText: { color: '#FFF', fontWeight: '800' }, secondary: { minHeight: 42, paddingHorizontal: 16, alignItems: 'center', justifyContent: 'center', borderRadius: 10, borderWidth: 1, borderColor: '#8DBADD', backgroundColor: '#FFF' }, secondaryText: { color: BLUETAP_COLORS.primary, fontWeight: '700' }, statCard:{minHeight:152,flexGrow:1,flexBasis:180},statIcon:{width:30,height:30,borderRadius:9,alignItems:'center',justifyContent:'center',backgroundColor:BLUETAP_COLORS.primarySoft},statIconGreen:{backgroundColor:'#E3F7EC'},statIconNavy:{backgroundColor:'#E5EDF5'},statIconText:{color:BLUETAP_COLORS.primary,fontWeight:'900',fontSize:12},statLabel:{color:BLUETAP_COLORS.textSecondary,fontSize:11,fontWeight:'800',letterSpacing:.35,marginTop:13,textTransform:'uppercase'},statValue:{color:BLUETAP_COLORS.textPrimary,fontWeight:'900',fontSize:28,marginTop:5},statDetail:{color:BLUETAP_COLORS.textSecondary,fontSize:12,marginTop:3},empty:{minHeight:180,alignItems:'center',justifyContent:'center',padding:24,borderWidth:1,borderStyle:'dashed',borderColor:BLUETAP_COLORS.border,borderRadius:12,backgroundColor:BLUETAP_COLORS.surfaceAlt},emptyTitle:{color:BLUETAP_COLORS.textPrimary,fontWeight:'800',fontSize:15},emptyDetail:{color:BLUETAP_COLORS.textSecondary,textAlign:'center',lineHeight:19,marginTop:6,maxWidth:320} });
