import React from 'react';
import { StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { BLUETAP_COLORS, BLUETAP_LAYOUT } from '../constants/bluetapTheme';

export function SectionCard({ children, style }) { return <View style={[dashboardStyles.card, style]}>{children}</View>; }
export function StatusBadge({ status = 'active' }) { const active = status === 'active' || status === 'enabled'; return <View style={[styles.badge, active ? styles.active : styles.inactive]}><Text style={[styles.badgeText, active ? styles.activeText : styles.inactiveText]}>{status}</Text></View>; }
export function PrimaryButton({ children, style, ...props }) { return <TouchableOpacity activeOpacity={0.85} style={[styles.primary, style]} {...props}><Text style={styles.primaryText}>{children}</Text></TouchableOpacity>; }
export function SecondaryButton({ children, style, textStyle, ...props }) { return <TouchableOpacity activeOpacity={0.85} style={[styles.secondary, style]} {...props}><Text style={[styles.secondaryText, textStyle]}>{children}</Text></TouchableOpacity>; }
export const dashboardStyles = StyleSheet.create({ card: { backgroundColor: BLUETAP_COLORS.surface, borderWidth: 1, borderColor: BLUETAP_COLORS.border, borderRadius: BLUETAP_LAYOUT.radius.lg, padding: 20, ...BLUETAP_LAYOUT.shadow }, title: { color: BLUETAP_COLORS.textPrimary, fontSize: 18, fontWeight: '800' }, body: { color: BLUETAP_COLORS.textSecondary, lineHeight: 20 }, label: { color: '#38566E', fontSize: 12, fontWeight: '700', marginBottom: 6 }, input: { minHeight: 46, borderWidth: 1, borderColor: '#BDD5E6', backgroundColor: BLUETAP_COLORS.surfaceAlt, borderRadius: 10, paddingHorizontal: 12, color: BLUETAP_COLORS.textPrimary, outlineStyle: 'none' } });
const styles = StyleSheet.create({ badge: { alignSelf: 'flex-start', borderRadius: 999, paddingHorizontal: 10, paddingVertical: 5 }, badgeText: { fontSize: 12, fontWeight: '800', textTransform: 'capitalize' }, active: { backgroundColor: '#E3F7EC' }, activeText: { color: BLUETAP_COLORS.success }, inactive: { backgroundColor: BLUETAP_COLORS.dangerSoft }, inactiveText: { color: BLUETAP_COLORS.danger }, primary: { minHeight: 44, paddingHorizontal: 18, alignItems: 'center', justifyContent: 'center', borderRadius: 10, backgroundColor: BLUETAP_COLORS.primary }, primaryText: { color: '#FFF', fontWeight: '800' }, secondary: { minHeight: 42, paddingHorizontal: 16, alignItems: 'center', justifyContent: 'center', borderRadius: 10, borderWidth: 1, borderColor: '#8DBADD', backgroundColor: '#FFF' }, secondaryText: { color: BLUETAP_COLORS.primary, fontWeight: '700' } });
